<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>KuaiKuaiLaunch</AssemblyName>
    <RootNamespace>KuaiKuaiLaunch</RootNamespace>
    <AssemblyTitle>快快启动</AssemblyTitle>
    <Product>快快启动</Product>
    <Version>0.0.1</Version>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <FileVersion>0.0.1.0</FileVersion>
    <InformationalVersion>beta V0.0.1</InformationalVersion>
    <PackageProjectUrl>https://github.com/peijiehuang/KuaiKuaiLaunch</PackageProjectUrl>
    <RepositoryUrl>https://github.com/peijiehuang/KuaiKuaiLaunch</RepositoryUrl>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\app.ico" />
    <Resource Include="assets\app.png" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
    <None Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

</Project>
